---
- name: Remove nginx app
  file:
    path: '{{ item }}'
    state: absent
  notify:
    - reload nginx
  with_items:
    - '/etc/nginx/sites-enabled/{{ instance_id }}.conf'
    - '/etc/nginx/sites-available/{{ instance_id }}.conf'

- name: Remove project folder
  file:
    path: '{{ dir_project }}'
    state: absent
