---
- include_tasks: config-non-ssl.yml
  when: not use_ssl

- include_tasks: config-ssl.yml
  when: use_ssl and not (ssl_cert_stat.stat.exists and ssl_key_stat.stat.exists)

- name: Enable nginx app
  file:
    src: '/etc/nginx/sites-available/{{ instance_id }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ instance_id }}.conf'
    state: link
  notify:
    - reload nginx
