---

- include_tasks: package.yml

- name: xxx
  debug:
    var: project_environment

- name: Check required variables
  assert:
    that:
      - project_environment|length > 0
      - project_name|length > 0
      - server_names|length > 0

- name: Make project id safe
  set_fact:
    instance_id: '{{ project_name }}-{{ project_environment }}'

- name: Configure paths
  set_fact:
    dir_fallback: '{{ projects_directory }}/{{ project_name }}/{{ project_environment }}/fallback'
    dir_project: '{{ projects_directory }}/{{ project_name }}'
    dir_ssl: '{{ projects_directory }}/{{ project_name }}/{{ project_environment }}/ssl'
    dir_versions: '{{ projects_directory }}/{{ project_name }}/versions'
    dir_env: '{{ projects_directory }}/{{ project_name }}/{{ project_environment }}'
    file_server_config: '{{ projects_directory }}/{{ project_name }}/{{ project_environment }}/server.conf'
    file_site_config: '/etc/nginx/sites-available/{{ instance_id }}.conf'
    file_site_fallback: '{{ projects_directory }}/{{ project_name }}/{{ project_environment }}/fallback/index.html'
    file_ssl_cert: '{{ projects_directory }}/{{ project_name }}/{{ project_environment }}/ssl/cert'
    file_ssl_fullchain: '{{ projects_directory }}/{{ project_name }}/{{ project_environment }}/ssl/fullchain'
    file_ssl_key: '{{ projects_directory }}/{{ project_name }}/{{ project_environment }}/ssl/key'

- name: Parse server names
  set_fact:
    dns_all: '{{ server_names.split(",") }}'

- name: Set main domain
  set_fact:
    dns_main: '{{ dns_all[0] }}'
    dns_other_names: '{{ dns_all | difference([dns_all[0]]) }}'

- include_tasks: config-present.yml
  when: state != 'absent'

- include_tasks: config-absent.yml
  when: state == 'absent'
