---

- include_tasks: package.yml

- name: Check required variables
  assert:
    that:
      - '{{ item }} is defined'
      - item
  with_items:
    - 'project_environment'
    - 'project_name'
    - 'server_names'

- name: Make project id safe
  set_fact:
    instance_id: '{{ project_name }}-{{ project_environment }}'

- name: Configure paths
  set_fact:
    dir_fallback: '{{ projects_directory }}/{{ project_name }}/{{ project_environment }}/fallback'
    dir_project: '{{ projects_directory }}/{{ project_name }}'
    dir_ssl: '{{ projects_directory }}/{{ project_name }}/ssl'
    dir_versions: '{{ projects_directory }}/{{ project_name }}/versions'
    dir_env: '{{ projects_directory }}/{{ project_name }}/{{ project_environment }}'
    file_server_config: '{{ projects_directory }}/{{ project_name }}/{{ project_environment }}/server.conf'
    file_site_config: '/etc/nginx/sites-available/{{ instance_id }}.conf'
    file_site_fallback: '{{ projects_directory }}/{{ project_name }}/{{ project_environment }}/fallback/index.html'
    file_ssl_cert: '{{ projects_directory }}/{{ project_name }}/ssl/cert'
    file_ssl_key: '{{ projects_directory }}/{{ project_name }}/ssl/key'

- name: Parse server names
  set_fact:
    dns_all: '{{ server_names.split(",") }}'

- name: Set main domain
  set_fact:
    dns_main: '{{ dns_all[0] }}'
    dns_other_names: '{{ dns_all | difference([dns_all[0]]) }}'

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Create project dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    group: '{{ group }}'
    owner: '{{ user }}'
  with_items:
    - '{{ dir_project }}'
    - '{{ dir_fallback }}'
    - '{{ dir_ssl }}'
    - '{{ dir_versions }}'
    - '{{ dir_env }}'

- name: Create fallback template
  template:
    src: index.html
    dest: '{{ file_site_fallback }}'

- name: Check SSL cert existence
  register: ssl_cert_stat
  stat:
    path: '{{ file_ssl_cert }}'
    follow: true

- name: Check SSL key existence
  register: ssl_key_stat
  stat:
    path: '{{ file_ssl_key }}'
    follow: true

- name: Check server file existence
  register: server_config_stat
  stat:
    path: '{{ file_server_config }}'
    follow: true

- name: Check config file existence
  register: config_file_stat
  stat:
    path: '{{ file_site_config }}'
    follow: true

- name: Configure server
  template:
    src: nginx-serve-content.conf
    dest: '{{ file_server_config }}'
  notify:
    - reload nginx
  when: not server_config_stat.stat.exists

- name: Configure nginx non-SSL config file
  template:
    src: nginx.conf
    dest: '{{ file_site_config }}'
  notify:
    - reload nginx
  when: not use_ssl or not config_file_stat.stat.exists

- include_tasks: config-ssl.yml
  when: use_ssl and not (ssl_cert_stat.stat.exists and ssl_key_stat.stat.exists)

- name: Enable nginx app
  file:
    src: '/etc/nginx/sites-available/{{ instance_id }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ instance_id }}.conf'
    state: link
  notify:
    - reload nginx
