---
- name: Read npm project meta
  delegate_to: localhost
  become: false
  include_vars:
    file: package.json
    name: npm
  failed_when: false

- name: Consume package.json
  include_tasks: package-npm.yml
  when: npm.name is defined

- name: Check for setup.py
  delegate_to: localhost
  become: false
  stat:
    path: setup.py
  register: setup_py_stat
  failed_when: false

- name: Consume setup.py
  include_tasks: package-python.yml
  when: setup_py_stat.stat.exists

- name: Use testing package version
  set_fact:
    project_version: '{{ project_version }}-{{ ansible_date_time.iso8601 | replace(":", "-") }}'
  when: project_environment != 'production' and project_version
