---
- name: Consume project name from package.json
  set_fact:
    project_name: '{{ npm.name }}'
  when: (project_name is not defined) or (project_name|length == 0)

- name: Consume project version from package.json
  set_fact:
    project_version: '{{ npm.version }}'
  when: (project_version is not defined) or (project_version|length == 0)
